firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('lorem/',views.first,name='lorem'),
    path('colors/',views.task,name='abcd'),
    path('home/',views.homepage,name='home'),
    path('users/',views.users,name='users'),

    path('admin/', admin.site.urls),
    path('',views.base,name='home'),
    path('myapp/',include('myapp.urls')),
    path('index/',views.index1,name='index'),
]

firstproject/myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('dashboard/',views.about,name='dashboard'),
    path('about/',views.about,name='ab'),
    path('contact/',views.contactView,name='con'),
    path('studentform/',views.empView,name='studentForm'),
    path('empform/',views.empView,name='employeeForm'),
    path('uslogin/',views.uslogin,name='uslogin'),
    path('rgUsingMF/',views.rgUsingMF,name='rgUsingMF'),
    path('usregister/',views.usregister,name='usregister'), 
    path('uslogout/',views.uslogout,name='logout'), 
    path('compdash/',views.compdash,name='compdash'),
    path('change_password/',views.change_password,name='comchange_password'),
    path('sendmail/',views.sendmail,name='sendmail'),

]

firstproject/myapp/forms.py
from django import forms
from myapp.models import employee
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.contrib.auth.models import User

class student(forms.Form):
    GEN = (('m','male'),('f','female'))

    name = forms.CharField(required=False,widget=forms.TextInput(attrs={'placeholder':'Please Enter Name Here..','class':'bg-dark'}))
    roll_number = forms.IntegerField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    gender = forms.ChoiceField(choices=GEN)
    dob = forms.DateField(widget = forms.DateInput(attrs={'type':'date'}))

## Validation function
def check_name(value):
    if value[0].lower() != 'a':
        raise ValidationError('Name Must Start with a')
    
class empForm(forms.ModelForm):
    name = forms.CharField(validators=[check_name,MaxLengthValidator(4)])
    class Meta():
        model = employee
        fields = '__all__'
        widgets = {
            'date_of_birth':forms.DateInput(attrs={'type':'date'}),
        }
class registerform(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields=('first_name','username','email','password')
        widgets = {
            'password':forms.PasswordInput()
        }
    def clean(self):
        data = super().clean()
        name = data['first_name']
        pas = data['password']
        cp = data['confirm_password']
        if pas != cp:
            raise ValidationError('Password Does Not Match')
            
        # if name.isalnum():
        #     raise ValidationError('Name should not contain digits')

firstproject/templates/about.html
{%extends "base.html"%}

{% block mystyle %}
    <style>
    h1{
        color: red;
        text-align: center;
    }
    </style>            
    
{% endblock %}
</div>
{%block mycode%}

<h1>ABOUT page</h1>

{% endblock %}

firstproject/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Site</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block mystyle %}
                
    {% endblock %}
    <style>
    .bg{
        background: url("{%static 'image/pubg.jpg'%}");
    }
    </style>
</div>
</head>
<body>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-12 px-0'>
                <nav class='navbar bg-primary navbar-expand-sm navbar-dark'>
                    <a href="{% url 'home' %}" class='navbar-brand'>MySiTe</a>
                   
                    <ul class='navbar-nav mx-auto'>
                        <li class='nav-item'>
                            <a href="{% url 'home' %}" class='nav-link'>Home</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'myapp:ab' %}" class='nav-link'>About</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'myapp:con'%}" class='nav-link'>Contact</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'admin:index' %}" class='nav-link'>Admin</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'myapp:studentForm' %}" class='nav-link'>Student Form</a>
                        </li>
                        <li class='nav-item'>
                            <a href="{% url 'myapp:employeeForm' %}" class='nav-link'>Model Form</a>
                        </li>
                       
                    </ul>
                </nav>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-3 bg-dark text-center py-5 text-light' style='height:740px;'>
                <img src="{%static 'image/is.jpg'%}" height='150' width='150' class='rounded-circle' alt="">
                <div class='py-5'>
                    <p>View Profile</p>
                    <p>Change Password</p>
                    <p>Notifications</p>
                    <p>
                        <a href="{% url 'myapp:logout' %}" >logout</a>
                    </p>
                </div>
            </div>
            <div class='col-md-9 bg px-0'>
                {% block mycode %}
                
    
                {% endblock %}
            </div>
            <!-- FOOTER -->
            <div class='col-md-12 bg-primary text-light py-3 text-center'>
                <h4>MySite</h4>
                <p>&copy; All rights reserved.| Designed By: sukhpreet singh</p>
            </div>
        </div>
        
    </div>
</body>
</html>

firstproject/templates/companydashbord.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> hi {{ user.username}}this is my dhhasdbord</h1>
    
</body>
</html>

firstproject/templates/employee.html
{% extends 'base.html' %}
{% block mystyle %}
{% load bootstrap4 %}
<style>
h2{font-family:courier New;color:white;}
label{color:white;}
</style>
{% endblock %}
{% block mycode %}
<h2>Employee form </h2>
<div style='height:2px;width:100px;background:red;'></div>
<div class='row p-4'>
    <div class='col-md-6 mx-auto' style='background:rgba(0,0,0,0.5)'>
        {% if msz %}
            <h2 class='alert alert-{{color}}'>{{msz}}</h2>
        {% endif %}
        <form action="" method='post'>
            {% csrf_token %}
            {% bootstrap_form frm%}
            <input type="submit" class='btn btn-primary m-2'>
        </form>
    </div>
</div>
{% endblock %}

firstproject/templates/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>firstproject | Homepage</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src='{% static "jquery.js"%}'></script>
    <script src='{% static "js/bootstrap.min.js"%}'></script>
</head>
<body>
    <div class='container bg-info'>
        <div class='row'>
            <div class='col-md-12 text-white bg-dark'>
                <h4>My Site</h4>
            </div>
        </div>
        <div class='row p-5'>
            <div class='col-md-4'>
                <div class='p-2 shadow shadow-lg'>
                    <img src="{% static 'images/bg.jpg'%}" height='200' width='100%' alt="">
                    <h2>Lorem Ipsum</h2>
                    <p>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non ad laboriosam autem. Ipsam illo impedit minima ipsum rem vitae corporis culpa, magni consectetur fugit neque suscipit autem. Natus, distinctio quos!
                    </p>
                </div>
            </div>
            <div class='col-md-4'>
                <div class='p-2 shadow shadow-lg'>
                    <a href="#" data-toggle='modal' data-target='#mymodal'>
                        <img src="{% static 'images/img2.png'%}" height="200" width="100%" alt="">
                    </a>
                    <h2>Lorem Ipsum</h2>
                    <div class='modal fade' id='mymodal'>
                        <div class='modal-dialog'>
                            <div class='modal-content'>
                                <div class='modal-header'>
                                    <span class='close' data-dismiss='modal'>&times;</span>
                                </div>
                                <div class='modal-body'>
                                    <p>
                                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non ad laboriosam autem. Ipsam illo impedit minima ipsum rem vitae corporis culpa, magni consectetur fugit neque suscipit autem. Natus, distinctio quos!
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class='col-md-4'>
                <div class='p-2 shadow shadow-lg'>
                    <img src="{% static 'images/img4.jpg'%}" height="200" width="100%" alt="">
                    <h2>Lorem Ipsum</h2>
                    <p>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Non ad laboriosam autem. Ipsam illo impedit minima ipsum rem vitae corporis culpa, magni consectetur fugit neque suscipit autem. Natus, distinctio quos!
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

firstproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        h1{
            font-family: cursive;color:rgb(225, 240, 12);text-align: center;
        }
        p{
            color:red;
        }
    </style>
</head>
<body>
    <h1>lorem</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatem optio accusantium, repellat, laborum sint cum porro, quasi illum suscipit et autem voluptatum aspernatur quae? Nesciunt enim corrupti dolores itaque. Veritatis.</p>
    <ol>
        <li>html</li>
        <li>css</li>
        <li>jAVA</li>
        <li>bootstrap</li>
        <li>python</li>
        <li>java</li>

    </ol>
    <hr>
    <h1>{{data}}</h1>
    <h1>{{data.upper}}</h1>
    <h1>{{data.lower}}</h1>
    <hr>
    <ol>
        {% for i in color %}
           <li>{{i}}</li>
        {% endfor %}
    </ol>
</body>
</html>

firstproject/templates/index1.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index Page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <style>
    .bg{
        background:url('{% static "image/pubg.jpg"%}');
        background-size:cover
    }
    .btn{
        height:100px;
    }
    </style>
</head>
<body class='bg py-5'>
    <div class='container py-5 my-5'>
        <div class='row py-5 my-5'>
            <div class='col-md-6'>
                <a href="{% url 'myapp:rgUsingMF'%}">
                    <button class='btn btn-danger btn-block'>Not Have an Account?</button>
                </a>
            </div>
            <div class='col-md-6'>
                <a href="{% url 'myapp:uslogin'%}">
                    <button class='btn btn-success btn-block'>Login</button>
                </a>
            </div>
        </div>
    </div>
</body>
</html>

firstproject/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
</head>
<body class="bg-light">
        <div class="container">
            <div class="row shadow-lg mt-5">
                <div class="col-md-6 p-5" style="background:#fff;">
                    <h1 class="mb-4 display-4">Login</h1>
                    <p>Don't have account <a href="">Create one </a> It's free and take only a minute. </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class='logininput mt-3' placeholder="Username" />
                        <input type="password" name="password" class='logininput mt-3' placeholder="Password" />
                        <input type="submit" value='Login' class="btn btn-success mt-5"/>
                        <label>rember me</label>
                        <input type="checkbox" name="remember" />
                    </form>
                    {% if status %}
                        <script>
                        alert('{{status}}');
                        </script>
                    {% endif %}
                </div>
                <div class="col-md-6" style='background:url("{% static 'image/pubg1.jpg' %}")'></div>
            </div>
        </div>
    </body>
</html>

firstproject/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Registration Page</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="{% static 'js/jquery.js' %}"></script>
    <style>
        .logininput{
            width:100%;
            height:40px;
            border:0px;
            border-bottom:2px solid #ccc;
        }
        .logininput:focus{
            box-shadow:none;
            outline: 0px;
        }
    </style>
</head>
<body class="bg-light">
    <div class="container">
        <div class="row shadow-lg my-5">
            <div class="col-md-6 p-5" style="background:#fff;">
                <h1 class="mb-5">Register</h1>
                <form method="post">
                    {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label>First Name</label>
                        <input type="text" class="form-control" name="first_name" />
                    </div>
                    <div class="col-md-6">
                        <label>Last Name</label>
                        <input type="text" class="form-control" name="last_name" />
                    </div>
                </div>
                <label>Username</label>
                <small class='text-danger' id='msz'></small>
                <input type="text" class="form-control" name="username" id='user'/>
                <label>Password</label>
                <input type="Password" class="form-control" name="password" />
                <label>Email</label>
                <input type="email" class="form-control" name="email" />
                <label for="">Address</label>
                <textarea class="form-control" name="address"></textarea>
                <label for="">Contact Number</label>
                <input type="number" class="form-control" name="contact" />
                <input type="submit" class="btn btn-success mt-3" />
                </form>
            </div>
            <div class="col-md-6" style='background:url("{% static 'image/pubg1.jpg' %}")'></div>
        </div>
    </div>
</body>
</html>

firstproject/templates/registration.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register Using Django User Model Form</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <style>
    .bg{
        background: url('{% static "image/pubg.jpg"%}');
    }
    </style>
</head> 
<body class='bg-light py-5'>
    <div class='container p-5 shadow-lg'>
        <div class='row'>
            <div class='col-md-6'>
                <form action="" method='post'>
                    {% csrf_token %}
                    {% bootstrap_form frm %}
                    <input type="submit" value='register' class='btn btn-success'>
                </form>
            </div>
            <div class='col-md-6 bg text-light text-center py-5'>
                <h2 class='my-5'>Fill Your Details</h2>
            </div>
        </div>
    </div>
    {% if status %}
    <script>
        alert('{{status}}');
    </script>
    {% endif %}
</body>
</html>

firstproject/templates/sendmail.html
{% extends "base.html"%}
{% block mycode %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            {%if status %}
                <p class="alert alert-success">{{status}}</p>
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">To</label>
                    <input type="text" class="form-control" name="to">
                </div>
                <div class="form-group">
                    <label for="">Subject</label>
                    <input type="text" class="form-control" name="subject">
                </div>
                <div class="form-group">
                    <label for="">Message</label>
                    <textarea class="form-control" name="message" id="" cols="30" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit"  class="btn btn-success" value="Send Mail">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

firstproject/templates/studentform.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block mystyle %}
    <style>
    label{
        color:blue;
    }
    /* #id_name{
        width:50%;
    } */
    </style>
{% endblock %}
{% block mycode %}
    <h1>Django Form</h1> 
    <!-- <table>
        {{form.as_table}}  
    </table>  -->
    <!-- {{form.as_p}} -->
    <div class='row'>
        <div class='col-md-8 mx-auto p-2 bg-light'>
            <form action="">
                {% bootstrap_form form %}
                <input type="submit" class='btn btn-primary'>
            </form>
        </div>
    </div>
{% endblock %}

firstproject/templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>task</title>
</head>
<body>
    <table >
        <thead>
            <th>color name</th>
            <th>color box</th>
        </thead>
       
<tbody>
        {% for i in c %}
        <tr>
            <td>{{i}}</td>
            <td>
                <div style="height:50px;width:100%;background:{{i}};"></div>
            </td>
        </tr>
        {% endfor %}
</tbody>  
    </table>
    {% for i in u %}
    <h1>{{i.r_no}}-{{i.name}}</h1>
    {% endfor %}
</body>
</html>

firstproject/templates/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Users</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
    .bg{
        background:url('{%static "images/img2.png"%}');
    }
    </style>
</head>
<body>
    <div class='container-fluid'>
        <div class='row bg'>
            <div class='col-md-12 text-center text-light px-0'>
                <h1 class='py-5 my-3'>myapp/users</h1>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-12'>
                <h2>Total Users: {{total}} </h2>
                <table class='table table-striped table-hover table-info'>
                    <thead class='thead-dark'>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Roll No</th>
                            <th>Date of Birth</th>
                            <th>Website</th>
                            <th>Address</th>
                            <th>Branch</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in users %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.name}}</td>
                                <td>{{i.email}}</td>
                                <td>{{i.roll_no}}</td>
                                <td>{{i.dob}}</td>
                                <td>{{i.website}}</td>
                                <td>{{i.address}}</td>
                                <td>{{i.branch}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>