myproject/myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    # path('dashboard/',views.about,name='dashboard'),
 
    path('contactView/',views.contactView,name='contactView'),
    path('login/',views.login,name='login'),
    path('about/',views.about,name='about'),
    # path('studentform/',views.empView,name='studentForm'),
    # path('empform/',views.empView,name='employeeForm'),
    path('uslogin/',views.uslogin,name='uslogin'),
    # path('rgUsingMF/',views.rgUsingMF,name='rgUsingMF'),
    path('register/',views.registerView,name='register'),
    path('check_user',views.check_user,name='check_user'),
    # path('uslogout/',views.uslogout,name='logout'), 
    # path('compdash/',views.compdash,name='compdash'),
    # path('change_password/',views.change_password,name='comchange_password'),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.base,name='base'),
    path('myapp/',include('myapp.urls')),
    path('index/',views.index,name='index'),
]

myproject/templates/about.html
{% extends 'base.html'%}
{% load staticfiles %}

{% block mystyle %}

{% endblock %}

{% block mycode %}
<div class="about-top section" id="about">
    <div class="container">
        <div class="w3l-about-top-head">
            <div class="col-md-6 about-left text-center">
                <h5 class="main-title">introducing</h5>
                <h6 class="txt">fitness freak</h6>
                <p>we explore your hidden potential</p>
            </div>
            <div class="col-md-6 about-right">
                <h5>Fitness culture is a sociocultural phenomenon which refers to the culture surrounding physical exercises. It is usually associated with gym culture, as doing physical exercises in locations such as gyms, wellness centres and health clubs is a popular activity. </h5>
                <p>Of course not. Instead, fitness was a way of life - it was survival. Hunting prey, foraging, farming and maintaining a home meant that people were constantly moving throughout the day. Despite the fact that these individuals never had any structured workout routines, they rarely suffered from some of the health problems that we see in today’s world. They ate all-natural foods that came from the ground or wild and sustained a high total daily calorie burn. These two combined factors produced a fit and healthy body - one that was agile, strong, and lean..</p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //about -->
<!-- about-bottom-grid -->
<div class="section about-bottomgrid">
    <div class="container">
        <div class="about-bot-grid-sec">
            <div class="about-middle-pos">
                <h2>fitness freak</h2>
                <p>strive for progress</p>
            </div>
            <div class="about-section">
                <div class="col-md-4 col-sm-6  abg1">

                </div>
                <div class="col-md-8 col-sm-6 wthree-sec-about">
                    <h4 class="bot-grid1">commit to be fit</h4>
                    <p class="bot-gridtxt">“Getting fit is all about mind over matter. I don’t mind, so it doesn’t matter.”</p>
                </div>
                <div class="clearfix"> </div>

            </div>
            <div class="col-md-8  col-sm-6 wthree-sec-about about-pos-btm">
                <h4 class="bot-grid-about">focus on being happy</h4>
                <p>Successful people maintain a positive focus in life no matter what is going on around them. My key to dealing with stress is simple: just stay cool and stay focused.</p>
            </div>
            <div class="col-md-4 col-sm-6 abg2">
            </div>

            <div class="clearfix"> </div>
        </div>
    </div>
</div>
{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html lang="zxx">

<head>
    <title>Fitness Freak Sports Category Bootstrap Responsive website Template | Home  :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Fitness Freak Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- Custom Theme files -->
    <link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet" media="all">
    <link href="{%static 'css/style.css'%}" type="text/css" rel="stylesheet" media="all">
    <!-- testimonials -->
    <link rel="stylesheet" href="{%static 'css/owl.carousel.css'%}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css'%}" type="text/css" media="all">
    <!-- flexslider -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css'%}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/smoothbox.css'%}" type='text/css' media="all" />
     <!-- font-awesome icons -->
    <link href="{% static 'css/font-awesome.css'%}" rel="stylesheet">
    <!-- //Custom Theme files -->
    <!-- web-fonts -->
    <link href="{% static '//fonts.googleapis.com/css?family=Jockey+One'%}" rel="stylesheet">
    <link href="{% static '//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i'%}" rel="stylesheet">
    <!-- //web-fonts -->
    <!-- Navigation-CSS --> <link rel="stylesheet" href= "{% static  'css/menu_sideslide.css'%}" 	type="text/css" media="all">
    {% block mystyle %}
                
    {% endblock %}
</head>

<body>
        <div class="agiletopbar">
                <div class="wthreenavigation">
                    <div class="menu-wrap">
                        <nav class="menu">
                            <div class="icon-list">
                                <a href="{% url 'index' % }"><i class="fa fa-home"></i><span>Home</span></a>
                                <a href="{% url 'myapp:about' % }"><i class="fa fa-info"></i><span>About</span></a>
                                <a class="scroll" href="#w3lsstatsaits"><i class="fa fa-bar-chart"></i><span>Stats</span></a>
                                <a class="scroll" href="#wthreedesserts"><i class="fa fa-birthday-cake"></i><span>Specials</span></a>
                                <a class="scroll" href="#portfolio"><i class="fa fa-picture-o"></i><span>Portfolio</span></a>
                                <a class="scroll" href="#chefw3agile"><i class="fa fa-user"></i><span>Chefs</span></a>
                                <a class="scroll" href="#agileinfofeedback"><i class="fa fa-comment-o"></i><span>Feedback</span></a>
                                <a class="scroll" href="#newsletter"><i class="fa fa-envelope-o"></i><span>Subscribe</span></a>
                                <a class="scroll" href="#aitscontactw3l"><i class="fa fa-phone"></i><span>Contact</span></a>
                            </div>
                        </nav>
                        <button class="close-button" id="close-button">Close Menu</button>
                    </div>
                    <button class="menu-button" id="open-button">Open Menu</button>
                </div>
                
              
               
                <div class="clearfix"></div>
            </div>
    <!-- banner -->
    <div class="main_section" id="home">
        <div class="agile-banner_nav">

            <nav class="navbar navbar-default">
                <div class="navbar-header navbar-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h1>
                        <a class="navbar-brand" href="{% url 'index'%}">Freak
                            <span>fitness</span>
                        </a>
                    </h1>

                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                    <nav class="link-effect-2" id="link-effect-2">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="{% url 'index' %}" class="effect-3">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'myapp:about' %}" class="effect-3 scroll">About</a>
                            </li>
                            <li>
                                <a href="{% url 'myapp:contactView'%}" class="effect-3 scroll">contact</a>

                            </li>
                            <li>
                                <a href="{% url 'myapp:uslogin'%}" class="effect-3 scroll">Log in</a>
                            </li>
                            <li>
                                <a href="{% url 'myapp:register'%}" class="effect-3 scroll">Register</a>
                            </li>
                           
                          
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">More
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li>
                                        <a href="{% static '#team'%}" class="scroll">Team</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{% static '#blog'%}" class="scroll">Blog</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a class="s-menu" href="{% static '#'%}">Sub menu
                                            <b class="fa fa-caret-right"></b>
                                        </a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li>
                                                <a href="{% static '#'%}">link1</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{% static '#'%}">link2</a>
                                            </li>
                                        </ul>
                                    </li>

                                </ul>
                            </li>
                         </ul>
                    </nav>
                </div>
            </nav>
            <div class="clearfix"> </div>
        </div>
    </div>
    <div style="height:200px;"></div>
        {% block mycode %}
                
        {% endblock %}

    <!-- footer -->
    <div class="footer-bottom">
        <div class="container">
            <div class="footer-copy text-center">
                <p>© 2018 Fitness Freak. All rights reserved | Design by
                    <a href="//w3layouts.com/">W3layouts</a>
                </p>
            </div>
        </div>
    </div>
<!-- //footer -->
    <!-- js -->
    <script src="js/jquery-2.2.3.min.js"></script>
    <!-- //js -->
    <!-- nav dropdown -->
    <script>
        $('ul.dropdown-menu li').hover(function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
        }, function () {
            $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
        });
    </script>
    <!-- //nav dropdown -->
    <!-- gallery -->
    <script src="js/smoothbox.jquery2.js"></script>
    <!-- //gallery -->
    <!-- banner Slider script  -->
    <script src="js/responsiveslides.min.js"></script>
    <script>
        $(function () {
            $("#slider, #slider1").responsiveSlides({
                auto: true,
                nav: false,
                speed: 1500,
                namespace: "callbacks",
                pager: true,
            });
        });
    </script>
    <!-- //banner Slider-JavaScript -->
    <!-- Team FlexSlider -->
    <script defer src="js/jquery.flexslider.js"></script>
    <script>
        $(window).load(function () {
            $('.flexslider').flexslider({
                animation: "slide",
                start: function (slider) {
                    $('body').removeClass('loading');
                }
            });
        });
    </script>
    <!-- End- Flexslider-script -->
    <!-- Testimonials owl carousel -->
    <script src="js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds
                autoPlay: false,
                items: 3,
                itemsDesktop: [991, 2],
                itemsDesktopSmall: [414, 4]

            });
        });
    </script>
    <!-- //Testimonials owl carousel -->
    <!-- start-smooth-scrolling -->
    <script src="js/move-top.js"></script>
    <script src="js/easing.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();

                $('html,body').animate({
                    scrollTop: $(this.hash).offset().top
                }, 1000);
            });
        });
    </script>
    <!-- //end-smooth-scrolling -->
    <!-- smooth-scrolling-of-move-up -->
    <script>
        $(document).ready(function () {
            /*
            var defaults = {
            	containerID: 'toTop', // fading element id
            	containerHoverID: 'toTopHover', // fading element hover id
            	scrollSpeed: 1200,
            	easingType: 'linear' 
            };
            */

            $().UItoTop({
                easingType: 'easeOutQuart'
            });

        });
    </script>
    <script src="{% static 'js/SmoothScroll.min.js'%}"></script>
    <!-- //smooth-scrolling-of-move-up -->
    <script src="{% static 'js/numscroller-1.0.js'%}"></script>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/bootstrap.js'%}"></script>
</body>

</html>

myproject/templates/contact.html
{% extends 'base.html'%}
{% block mystyle %}

{% endblock %}
{% block mycode %}
        <div class="section" id="contact">
                <h3 class="title1 text-center">Contact Us</h3>
                <div class="container-fluid">
                    <div class="map-grid">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6509687.090753893!2d-123.76387427440008!3d37.18697025540024!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb9fe5f285e3d%3A0x8b5109a227086f55!2sCalifornia%2C+USA!5e0!3m2!1sen!2sin!4v1491201047627"
                            style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="w3layouts-contact-pos">
                    <div class="w3layouts-contact-pos-grid">
                        <span class="field-icon fa fa-map-marker" aria-hidden="true"></span>
                        <ul>
                            <li>3515 Carriage Court</li>
                            <li>Palm Springs</li>
                            <li>California.</li>
                        </ul>
                    </div>
                    <div class="w3layouts-contact-pos-grid sr1">
                        <span class="field-icon fa fa-phone" aria-hidden="true"></span>
                        <ul>
                            <li>+91 9915448908</li>
                            <li>+91 8427703682</li>
                            <li>+91 8437578731</li>
                        </ul>
                    </div>
                    <div class="w3layouts-contact-pos-grid sr2">
                        <span class="field-icon fa fa-envelope-o fa-lg" aria-hidden="true"></span>
                        <ul>
                            <li>
                                <a href="mailto:info@example.com">info@example.com</a>
                            </li>
                            <li>
                                <a href="mailto:info@example.com">info@example.com</a>
                            </li>
                            <li>
                                <a href="mailto:info@example.com">info@example.com</a>
                            </li>
                        </ul>
                    </div>
                    <div class="w3layouts-contact-pos-grid">
                        <span class="field-icon fa fa-clock-o" aria-hidden="true"></span>
                        <ul>
                            <li>Monday-Friday :
                                <span> 07:00 AM-22:00 PM</span>
                            </li>
                            <li>saturday :
                                <span>06:00 AM-23:00 PM</span>
                            </li>
                            <li>sunday :
                                <span>06:00 AM-23:00 PM</span>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="contact-form">
                    <div class="container">
        
                        <form action="" method="post">
                                {% csrf_token %}
                                {% if result %}
                                    <script>
                                        alert('{{status}}');
                                    </script>
                                {% endif %}

                            <div class="contact-left-form">
                                <div class="field-input">
                                    <span class="field-icon fa fa-user" aria-hidden="true"></span>
                                    <input type="text" placeholder="Name" name="name" required="">
                                    <div class="clearfix"></div>
                                </div>
                                <div class="field-input">
                                    <span class="field-icon  fa fa-envelope-o fa-lg" aria-hidden="true"></span>
                                    <input type="email" placeholder="Email" name="email" class="email" required="">
                                    <div class="clearfix"></div>
                                </div>
                             
                            </div>
                            <div class="clear"></div>
                            <textarea placeholder="Your Message" name="message" required=""></textarea>
                            <button class="btn1">Submit message</button>
                            
                        </form>
                    </div>
                </div>
            </div>
            {% endblock %}

myproject/templates/register.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}
<html lang="zxx">

<head>
    <title>Fitness Freak </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Fitness Freak Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
	</script>

    <link rel="stylesheet" href="{% static 'css/style2.css'%}" type="text/css" media="all">
   
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" type="text/css" media="all">
   
	<link href="{% static '//fonts.googleapis.com/css?family=Quattrocento+Sans:400,400i,700,700i'%}" rel="stylesheet">
	<link href="{% static '//fonts.googleapis.com/css?family=Mukta:200,300,400,500,600,700,800'%}" rel="stylesheet">
    <!-- Custom Theme files -->
    <link href="{% static 'css/bootstrap.css'%}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static 'css/style.css'%}" type="text/css" rel="stylesheet" media="all">
    <!-- testimonials -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css'%}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/owl.theme.css'%}" type="text/css" media="all">
    <!-- flexslider -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/smoothbox.css' %}" type='text/css' media="all" />
     <!-- font-awesome icons -->
    <link href="{% static 'css/font-awesome.css'%}" rel="stylesheet">
    <!-- //Custom Theme files -->
    <!-- web-fonts -->
    <link href="{% static '//fonts.googleapis.com/css?family=Jockey+One'%}" rel="stylesheet">
    <link href="{%static '//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i'%}" rel="stylesheet">
	<!-- //web-fonts -->
	<script src="{% static 'jquery.js' %}"></script>
</head>

<body>
    <!-- banner -->
    <div class="main_section" id="home">
        <div class="agile-banner_nav">

            <nav class="navbar navbar-default">
                <div class="navbar-header navbar-left">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <h1>
                        <a class="navbar-brand" href="{% url 'index'%}">Freak
                            <span>&nbsp;itness</span>
                        </a>
                    </h1>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                    <nav class="link-effect-2" id="link-effect-2">
                        <ul class="nav navbar-nav">
                            <li class="active">
                                <a href="{% url 'index'%}" class="effect-3">Home</a>
                            </li>
                            <li>
                                <a href="#about" class="effect-3 scroll">About</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle effect-3" data-toggle="dropdown">More
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">

                                    <li>
                                        <a href="#team" class="scroll">Team</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="#blog" class="scroll">Blog</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a class="s-menu" href="#">Sub menu
                                            <b class="fa fa-caret-right"></b>
                                        </a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li>
                                                <a href="#">link1</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="#">link2</a>
                                            </li>
                                        </ul>
                                    </li>

                                </ul>
                            </li>


                            <li>
                                <a href="{% url 'myapp:contactView'%}" >contact</a>

                            </li>
                            <li>
                                <a href="{% url 'myapp:uslogin'%}">Log in</a>
                            </li>
                            <li>
                                <a href="{% url 'myapp:register'%}">Register</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </nav>
            <div class="clearfix"> </div>
        </div>
<section class="main1">
	<div class="layer"></div>
		<div class="content-w3ls">
			<div class="text-center icon">
				<span class="fa fa-html5"></span>
			</div>
			<div class="content-bottom">
				<form  method="post">
						{% csrf_token %}
					<div class="field-group">
						<span class="fa fa-user" aria-hidden="true"></span>
						<div class="wthree-field">
							<input name="name" id="text1" type="text" value="" placeholder=" Name" required>
						</div>
					</div>
					<div class="field-group">
						<span class="fa fa-user" aria-hidden="true"></span>
						<div class="wthree-field">
							<input name="contact" id="text1" type="text" value="" placeholder=" Mobile number" required>
						</div>
					</div>
					<div class="field-group">
						<span class="fa fa-lock" aria-hidden="true"></span>
						<div class="wthree-field">
							<input name="email" id="myInput" type="email" placeholder="Email">
						</div>
                    </div>
                            <div class="field-group">
						<span class="fa fa-lock" aria-hidden="true"></span>
						<div class="wthree-field">
							<input name="password" id="myInput" type="password" placeholder="Password">
						</div>
                    </div>
                    <div class="field-group">
						<span class="fa fa-lock" aria-hidden="true"></span>
						<div class="wthree-field">
							<input name="Cpassword" id="myInput" type="password" placeholder="Confirm password">
                        </div>
                        
                    </div>
                </div>
					
					<div class="wthree-field">
						<button type="submit" class="btn">submit</button>
					</div>
				</form>

			</div>
		</div>
		</div>
		<div>
				{% if status %}
				<script>
					alert('{{status}}');
				</script>
				{% endif %}
		</div>
</section>

    <!-- footer -->
		<div class="footer-bottom">
			<div class="container">
					<div class="footer-copy text-center">
							<p> 
					© 2019 Fitness Freak. All rights reserved | Design by: Jaspreet Singh
							</p>
					</div>
			</div>
	</div>
<!-- //footer -->
	<!-- js -->
	<script src="{% static 'js/jquery-2.2.3.min.js'%}"></script>
	<!-- //js -->
	<!-- nav dropdown -->
	<script>
			$('ul.dropdown-menu li').hover(function () {
					$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
			}, function () {
					$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
			});
	</script>
	<!-- //nav dropdown -->
	<!-- gallery -->
	<script src="{% static 'js/smoothbox.jquery2.js'%}"></script>
	<!-- //gallery -->
	<!-- banner Slider script  -->
	<script src="{% static 'js/responsiveslides.min.js'%}"></script>
	<script>
			$(function () {
					$("#slider, #slider1").responsiveSlides({
							auto: true,
							nav: false,
							speed: 1500,
							namespace: "callbacks",
							pager: true,
					});
			});
	</script>
	<!-- //banner Slider-JavaScript -->
	<!-- Team FlexSlider -->
	<script defer src="{% static 'js/jquery.flexslider.js'%}"></script>
	<script>
			$(window).load(function () {
					$('.flexslider').flexslider({
							animation: "slide",
							start: function (slider) {
									$('body').removeClass('loading');
							}
					});
			});
	</script>
	<!-- End- Flexslider-script -->
	<!-- Testimonials owl carousel -->
	<script src="{% static 'js/owl.carousel.js'%}"></script>
	<script>
			$(document).ready(function () {
					$("#owl-demo").owlCarousel({

							autoPlay: 3000, //Set AutoPlay to 3 seconds
							autoPlay: false,
							items: 3,
							itemsDesktop: [991, 2],
							itemsDesktopSmall: [414, 4]

					});
			});
	</script>
	<!-- //Testimonials owl carousel -->
	<!-- start-smooth-scrolling -->
	<script src="{% static 'js/move-top.js'%}"></script>
	<script src="{% static 'js/easing.js'%}"></script>
	<script>
			jQuery(document).ready(function ($) {
					$(".scroll").click(function (event) {
							event.preventDefault();

							$('html,body').animate({
									scrollTop: $(this.hash).offset().top
							}, 1000);
					});
			});
	</script>
	<!-- //end-smooth-scrolling -->
	<!-- smooth-scrolling-of-move-up -->
	<script>
			$(document).ready(function () {
					/*
					var defaults = {
						containerID: 'toTop', // fading element id
						containerHoverID: 'toTopHover', // fading element hover id
						scrollSpeed: 1200,
						easingType: 'linear' 
					};
					*/

					$().UItoTop({
							easingType: 'easeOutQuart'
					});

			});
	</script>
	<script src="{% static 'js/SmoothScroll.min.js'%}"></script>
	<!-- //smooth-scrolling-of-move-up -->
	<script src="{% static 'js/numscroller-1.0.js'%}"></script>
	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="{% static 'js/bootstrap.js'%}"></script>
	<script>
		$(function(){
			$('#user').keyup(function(){
				uname = $(this).val();
				$.ajax({
					url:'{% url "myapp:check_user"%}',
					type:'get',
					data:{username:uname},
					success:function(data){
						if(data=="Username Validation Success!!!"){
							$("#submit").removeAttr('disabled');
							$('#msz').removeClass('text-danger').addClass('text-success').html(data);
						}else{
							$("#submit").attr('disabled','disabled');
							$('#msz').removeClass('text-success').addClass('text-danger').html(data);
	
	
						}
					   
					}
				})
			});
		});
		</script>
		{% if status %}
			<script>
			alert('{{status}}');
			</script>
		{% endif %}
</body>
</html>